# Generated by Django 3.2.8 on 2021-10-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211018_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='blog_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='blog_title',
        ),
    ]
