# Generated by Django 3.2.8 on 2021-10-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211018_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='blog_Project',
        ),
    ]
