# Generated by Django 3.2.8 on 2021-10-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_project_blog_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_Project',
            new_name='Project',
        ),
    ]
