# Generated by Django 3.2.8 on 2021-10-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_project_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='blog_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='blog_title',
            new_name='title',
        ),
    ]
